### ISSUE TITLE
Video Downloader not adding videos to the list

### ISSUE THREAD

**Issue by Baegus** [ozok/TEncoder#2]
I tried downloading some videos, but everytime I paste a link in the Video Downloader, it just loads for a while and doesn't add anything to the list. Am I missing something?

The Main log shows this:
[8. 3. 2015 21:01:30] Unable to add [URL]. (Couldn't find any formats)

youtube-dl works normally with the same URLs (after I point it to ffmpeg.exe).

Also, the version of youtube-dl bundled with TEncoder seems to be a little outdated, there's a new one available (I tried to manually update it, but it didn't solve the issue I'm describing there).

**Comment by ozok** [comment]
youtube-dl output parser was unable to extract formats. I've fixed it with the latest commit.
https://github.com/ozok/TEncoder/blob/master/Units/DownloaderUnits/UnitYouTubeVideoInfoExtractor.pas#L321

**Comment by Baegus** [comment]
Great! Thanks!

**Comment by Baegus** [comment]
Well, now it adds videos, but it won't download them. It seems like the audio format is set to "mp4" (DASH videos are ok, this happens to all non-DASH videos):

[debug] Command-line args: ['-o', 'C:\Users\Baegus\Desktop\Downloaded\%(uploader)s - %(title)s.%(ext)s', '-i', '--no-playlist', '-x', '--audio-format', 'mp4', '-v', '-c', '-w', '[URL]']
Usage:  [OPTIONS] URL [URL...]

: error: invalid audio format specified

**Comment by ozok** [comment]
I made a typo. I'll release a new fix in a few days time.

**Comment by Baegus** [comment]
Awesome.

Oh, and BTW, do you accept translations somehow? I could translate TEncoder to Czech, but your Crowdin page is closed down.

**Comment by ozok** [comment]
No, there are currently no efforts for translations.
Main problem with video download is also fixed in the latest commit.
